# Form implementation generated from reading ui file 'monitor_data_new.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_monitor_data_new(object):
    def setupUi(self, user_monitor_data_new):
        user_monitor_data_new.setObjectName("user_monitor_data_new")
        user_monitor_data_new.resize(867, 600)
        self.centralwidget = QtWidgets.QWidget(parent=user_monitor_data_new)
        self.centralwidget.setObjectName("centralwidget")
        user_monitor_data_new.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=user_monitor_data_new)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 22))
        self.menubar.setObjectName("menubar")
        user_monitor_data_new.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=user_monitor_data_new)
        self.statusbar.setObjectName("statusbar")
        user_monitor_data_new.setStatusBar(self.statusbar)

        self.retranslateUi(user_monitor_data_new)
        QtCore.QMetaObject.connectSlotsByName(user_monitor_data_new)

    def retranslateUi(self, monitor_data_new):
        _translate = QtCore.QCoreApplication.translate
        monitor_data_new.setWindowTitle(_translate("user_monitor_data_new", "MainWindow"))
