# Form implementation generated from reading ui file 'tab2_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tab2_window(object):
    def setupUi(self, tab2_window):
        tab2_window.setObjectName("tab2_window")
        tab2_window.resize(929, 592)
        self.centralwidget = QtWidgets.QWidget(parent=tab2_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 921, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setObjectName("top_layout")
        self.now_data_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.now_data_label.sizePolicy().hasHeightForWidth())
        self.now_data_label.setSizePolicy(sizePolicy)
        self.now_data_label.setObjectName("now_data_label")
        self.top_layout.addWidget(self.now_data_label)
        self.tab_2_mouse_cage_combox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2_mouse_cage_combox.sizePolicy().hasHeightForWidth())
        self.tab_2_mouse_cage_combox.setSizePolicy(sizePolicy)
        self.tab_2_mouse_cage_combox.setMinimumSize(QtCore.QSize(100, 0))
        self.tab_2_mouse_cage_combox.setSizeIncrement(QtCore.QSize(0, 0))
        self.tab_2_mouse_cage_combox.setBaseSize(QtCore.QSize(0, 0))
        self.tab_2_mouse_cage_combox.setObjectName("tab_2_mouse_cage_combox")
        self.tab_2_mouse_cage_combox.addItem("")
        self.top_layout.addWidget(self.tab_2_mouse_cage_combox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.top_layout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.top_layout)
        self.content_layout = QtWidgets.QHBoxLayout()
        self.content_layout.setContentsMargins(-1, -1, 0, -1)
        self.content_layout.setObjectName("content_layout")
        self.content_layout_son = QtWidgets.QVBoxLayout()
        self.content_layout_son.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.content_layout_son.setObjectName("content_layout_son")
        self.content_layout.addLayout(self.content_layout_son)
        self.verticalLayout.addLayout(self.content_layout)
        self.verticalLayout.setStretch(1, 6)
        tab2_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=tab2_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 22))
        self.menubar.setObjectName("menubar")
        tab2_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=tab2_window)
        self.statusbar.setObjectName("statusbar")
        tab2_window.setStatusBar(self.statusbar)

        self.retranslateUi(tab2_window)
        QtCore.QMetaObject.connectSlotsByName(tab2_window)

    def retranslateUi(self, tab2_window):
        _translate = QtCore.QCoreApplication.translate
        tab2_window.setWindowTitle(_translate("tab2_window", "MainWindow"))
        self.now_data_label.setText(_translate("tab2_window", "当前数据源："))
        self.tab_2_mouse_cage_combox.setItemText(0, _translate("tab2_window", "大鼠1"))
