# Form implementation generated from reading ui file 'monitor_data_new.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_monitor_data_new(object):
    def setupUi(self, monitor_data_new):
        monitor_data_new.setObjectName("monitor_data_new")
        monitor_data_new.resize(867, 600)
        self.centralwidget = QtWidgets.QWidget(parent=monitor_data_new)
        self.centralwidget.setObjectName("centralwidget")
        monitor_data_new.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=monitor_data_new)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 22))
        self.menubar.setObjectName("menubar")
        monitor_data_new.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=monitor_data_new)
        self.statusbar.setObjectName("statusbar")
        monitor_data_new.setStatusBar(self.statusbar)
        self.left_top_dock_widget = QtWidgets.QDockWidget(parent=monitor_data_new)
        self.left_top_dock_widget.setObjectName("left_top_dock_widget")
        self.left_top_dock_widget_son = QtWidgets.QWidget()
        self.left_top_dock_widget_son.setObjectName("left_top_dock_widget_son")
        self.left_top_dock_widget.setWidget(self.left_top_dock_widget_son)
        monitor_data_new.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.left_top_dock_widget)
        self.right_top_dock_widget = QtWidgets.QDockWidget(parent=monitor_data_new)
        self.right_top_dock_widget.setObjectName("right_top_dock_widget")
        self.right_top_dock_widget_son = QtWidgets.QWidget()
        self.right_top_dock_widget_son.setObjectName("right_top_dock_widget_son")
        self.right_top_dock_widget.setWidget(self.right_top_dock_widget_son)
        monitor_data_new.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.right_top_dock_widget)
        self.left_bottom_dock_widget = QtWidgets.QDockWidget(parent=monitor_data_new)
        self.left_bottom_dock_widget.setObjectName("left_bottom_dock_widget")
        self.left_bottom_widget_son = QtWidgets.QWidget()
        self.left_bottom_widget_son.setObjectName("left_bottom_widget_son")
        self.left_bottom_dock_widget.setWidget(self.left_bottom_widget_son)
        monitor_data_new.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.left_bottom_dock_widget)
        self.right_bottom_dock_widget = QtWidgets.QDockWidget(parent=monitor_data_new)
        self.right_bottom_dock_widget.setObjectName("right_bottom_dock_widget")
        self.right_bottom_dock_widget_son = QtWidgets.QWidget()
        self.right_bottom_dock_widget_son.setObjectName("right_bottom_dock_widget_son")
        self.right_bottom_dock_widget.setWidget(self.right_bottom_dock_widget_son)
        monitor_data_new.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.right_bottom_dock_widget)

        self.retranslateUi(monitor_data_new)
        QtCore.QMetaObject.connectSlotsByName(monitor_data_new)

    def retranslateUi(self, monitor_data_new):
        _translate = QtCore.QCoreApplication.translate
        monitor_data_new.setWindowTitle(_translate("monitor_data_new", "MainWindow"))
