# Form implementation generated from reading ui file 'content.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_content_window(object):
    def setupUi(self, content_window):
        content_window.setObjectName("content_window")
        content_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=content_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_layout = QtWidgets.QVBoxLayout()
        self.left_layout.setObjectName("left_layout")
        self.horizontalLayout.addLayout(self.left_layout)
        self.middle_layout = QtWidgets.QVBoxLayout()
        self.middle_layout.setContentsMargins(-1, 0, -1, 0)
        self.middle_layout.setObjectName("middle_layout")
        self.content_layout = QtWidgets.QVBoxLayout()
        self.content_layout.setObjectName("content_layout")
        self.middle_layout.addLayout(self.content_layout)
        self.middle_layout.setStretch(0, 5)
        self.horizontalLayout.addLayout(self.middle_layout)
        self.right_layout = QtWidgets.QVBoxLayout()
        self.right_layout.setObjectName("right_layout")
        self.horizontalLayout.addLayout(self.right_layout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.bottom_layout = QtWidgets.QVBoxLayout()
        self.bottom_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.bottom_layout.setObjectName("bottom_layout")
        self.verticalLayout.addLayout(self.bottom_layout)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 1)
        content_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=content_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        content_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=content_window)
        self.statusbar.setObjectName("statusbar")
        content_window.setStatusBar(self.statusbar)

        self.retranslateUi(content_window)
        QtCore.QMetaObject.connectSlotsByName(content_window)

    def retranslateUi(self, content_window):
        _translate = QtCore.QCoreApplication.translate
        content_window.setWindowTitle(_translate("content_window", "MainWindow"))
